<?php
// api/config.php

header('Content-Type: application/json');
header('Access-Control-Allow-Origin: *');

// For local testing, we are using the SQLite database generated by the Python pipeline.
// For production cPanel deployment, switch this back to the MySQL connection below.

$db_path = __DIR__ . '/../data/cleaned/vector_predictor.db';
$dsn = "sqlite:$db_path";

/* 
// -- PRODUCTION MYSQL SETTINGS --
$host = 'localhost';
$db   = 'vector_predictor';
$user = 'root';
$pass = '';
$charset = 'utf8mb4';
$dsn = "mysql:host=$host;dbname=$db;charset=$charset";
*/

$options = [
    PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,
    PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
    PDO::ATTR_EMULATE_PREPARES   => false,
];

try {
    // SQLite doesn't need user/pass, but we can pass null
    $pdo = new PDO($dsn, null, null, $options);
} catch (\PDOException $e) {
    echo json_encode(['error' => 'Database connection failed: ' . $e->getMessage()]);
    exit;
}
?>
